# Workflow para deploy de site estático no GitHub Pages
name: Deploy static site to Pages

on:
  # Executa quando há push na branch principal
  push:
    branches: ["main"]

  # Permite rodar manualmente
  workflow_dispatch:

# Permissões necessárias
permissions:
  contents: read
  pages: write
  id-token: write

# Evita múltiplos deploys concorrentes
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Enviar artefato
        uses: actions/upload-pages-artifact@v3
        with:
          # Caminho da pasta onde está o index.html
          path: ./

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
